export async function seed(knex) {
  await knex('excodes').insert([
    { abbr: 'USD', name: 'United States Dollar' },
    { abbr: 'AUD', name: 'Australian Dollar' },
    { abbr: 'BGN', name: 'Bulgarian Lev' },
    { abbr: 'BRL', name: 'Brazilian Real' },
    { abbr: 'CAD', name: 'Canadian Dollar' },
    { abbr: 'CHF', name: 'Swiss Franc' },
    { abbr: 'CNY', name: 'Chinese Yuan' },
    { abbr: 'CZK', name: 'Czech Republic Koruna' },
    { abbr: 'DKK', name: 'Danish Krone' },
    { abbr: 'GBP', name: 'British Pound Sterling' },
    { abbr: 'HKD', name: 'Hong Kong Dollar' },
    { abbr: 'HRK', name: 'Croatian Kuna' },
    { abbr: 'HUF', name: 'Hungarian Forint' },
    { abbr: 'IDR', name: 'Indonesian Rupiah' },
    { abbr: 'ILS', name: 'Israeli New Sheqel' },
    { abbr: 'INR', name: 'Indian Rupee' },
    { abbr: 'JPY', name: 'Japanese Yen' },
    { abbr: 'KRW', name: 'South Korean Won' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
    { abbr: '', name: '' },
  ])
}
